buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'org.jetbrains.changelog'
    id 'net.researchgate.release'
    id 'jacoco'
    id 'org.sonarqube'
}

tasks.register('allWrappers', Wrapper) {
    gradleVersion = "${project.property('gradle.version')}"
}

apply from: "${rootProject.projectDir}/gradle/changelog.gradle"

release {
    tagTemplate = 'v${version}'
    git {
        requireBranch.set('main')
    }
}
tasks.afterReleaseBuild.dependsOn tasks.patchChangelog

subprojects {
    group = 'dk.sunepoulsen.tes'
    version = "${project.property('version')}"

    repositories {
        mavenLocal()
        mavenCentral()

        maven {
            url = "$mavenRepositoryBaseUrl/$mavenRepositorySnapshots"
            allowInsecureProtocol = true
        }
        maven {
            url = "$mavenRepositoryBaseUrl/$mavenRepositoryReleases"
            allowInsecureProtocol = true
        }
    }

    apply plugin: 'java'
    apply plugin: 'groovy'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(project.property('java.version').toString())
        }
    }

    dependencies {
        // Lombok
        compileOnly 'org.projectlombok:lombok:1.18.44'
        annotationProcessor 'org.projectlombok:lombok:1.18.44'

        // Logging
        implementation 'ch.qos.logback:logback-core:1.5.32'
        implementation 'ch.qos.logback:logback-classic:1.5.32'
        implementation 'org.slf4j:log4j-over-slf4j:2.0.17'

        // Spock
        testImplementation 'org.apache.groovy:groovy-all:5.0.4'
        testImplementation 'org.spockframework:spock-core:2.4-groovy-5.0'
        testImplementation 'net.bytebuddy:byte-buddy:1.18.7'
        testImplementation 'org.objenesis:objenesis:3.5'
    }

    apply from: "${rootProject.projectDir}/gradle/resources.gradle"

    test {
        useJUnitPlatform()
    }

    apply from: "${rootProject.projectDir}/gradle/sonarqube-java.gradle"
}

sonar {
    properties {
        property "sonar.projectName", "TES Features"
        property "sonar.projectKey", "tes-features"

        property 'sonar.coverage.exclusions', [
            // Deployment
            '**/dk/sunepoulsen/tes/features/deployment/**',

            // Service
            '**/dk/sunepoulsen/tes/features/service/Application.java',
            '**/dk/sunepoulsen/tes/features/service/configuration/**',
            '**/dk/sunepoulsen/tes/features/service/domains/tests/**',

            // Tests
            '**/dk/sunepoulsen/tes/features/ct/**',
        ]

        property 'sonar.dependencyCheck.severity.blocker', '9.0'
        property 'sonar.dependencyCheck.severity.critical', '7.0'
        property 'sonar.dependencyCheck.severity.major', '4.0'
        property 'sonar.dependencyCheck.severity.minor', '0.0'
    }
}
