# ============================================================================================
#                           Versions
# ============================================================================================

# Repo versions
version=1.0.0-SNAPSHOT

# Build versions
gradle.version=9.4
java.version=25

# ============================================================================================
#                           Backend Service Properties
# ============================================================================================

service.name=tes-features
service.docker.image.name=tes-features-service

# ============================================================================================
#                           TLS Certificate Properties
# ============================================================================================

service.tls.certificate.alias=tes

# ============================================================================================
#                           Docker Images
# ============================================================================================

# Base image for backend modules
backend.module.base.image.name=eclipse-temurin
backend.module.base.image.tag=25-jre-alpine
