# ===================================================================
#                   Logging configuration
# ===================================================================

logging:
  level:
    dk.sunepoulsen.tes: INFO
  pattern:
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%6p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([%X{X-OPERATION-ID}]){yellow} %clr([%X{X-TRANSACTION-ID}]){yellow} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: "${FILE_LOG_PATTERN:%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%6p} ${PID:- } --- [%t] %-40.40logger{39} [%X{X-OPERATION-ID}] [%X{X-TRANSACTION-ID}] : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"

# ===================================================================
#                   Actuator configuration
# ===================================================================

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: @serviceName@
    version: @version@
    service:
      name: @projectName@

# ===================================================================
#                   Swagger configuration
# ===================================================================

springdoc:
  show-actuator: true
  default-produces-media-type: application/json
  model-converters:
    pageable-converter:
      enabled: true

# ===================================================================
#                   SSL configuration
# ===================================================================

server:
  ssl:
    enabled: true

    # The alias mapped to the certificate
    key-alias: @certificateAlias@

    # The format used for the keystore. It could be set to JKS in case it is a JKS file
    key-store-type: PKCS12

# ===================================================================
#                   Spring JPA Configuration
# ===================================================================

spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    default-schema: features
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
