# ===================================================================
#                   Run Configuration
# ===================================================================

server.port=19080

# ===================================================================
#                   Logging Configuration
# ===================================================================

logging.level.dk.sunepoulsen.tes=DEBUG

logging.file.name=@projectBuildDir@/logs/@projectName@.log

# ===================================================================
#                   Actuator Configuration
# ===================================================================

management.endpoints.web.exposure.include=health,info,env,metrics

management.endpoint.health.show-details=ALWAYS
management.health.db.enabled=true
management.info.env.enabled=true
management.endpoint.env.show-values=ALWAYS

# ===================================================================
#                   SSL Configuration
# ===================================================================

server.ssl.enabled=false

# ===================================================================
#                   Spring JPA Configuration
# ===================================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:file:./tes-features-service/build/test-data/test-db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=org.h2.Driver
