plugins {
    id 'java-library'
}

dependencies {
    // Tech Easy Solutions
    api 'dk.sunepoulsen.tes-foundation:tes-rest-models:3.0.0-SNAPSHOT'

    testImplementation 'dk.sunepoulsen.tes-foundation:tes-data-generators:3.0.0-SNAPSHOT'
    testImplementation 'dk.sunepoulsen.tes-foundation:tes-validation-tests:3.0.0-SNAPSHOT'

    // Hibernate Validation
    testImplementation 'org.hibernate.validator:hibernate-validator:8.0.1.Final'
    testImplementation 'org.apache.tomcat.embed:tomcat-embed-el:11.0.18'
}

apply from: "${rootProject.projectDir}/gradle/publish.gradle"
