plugins {
    id 'java-library'
}

dependencies {
    api project(':tes-features-integrator')
    implementation 'dk.sunepoulsen.tes-foundation:tes-deployment-core:3.0.0-SNAPSHOT'
    implementation 'dk.sunepoulsen.tes-foundation:tes-io:3.0.0-SNAPSHOT'
    implementation 'dk.sunepoulsen.tes-foundation:tes-sut-engine:3.0.0-SNAPSHOT'
    implementation 'dk.sunepoulsen.tes-foundation:tes-rest-integrations:3.0.0-SNAPSHOT'
    implementation 'dk.sunepoulsen.tes-foundation:tes-wiremock-deployment:1.0.0-SNAPSHOT'
    implementation 'dk.sunepoulsen.tes-foundation:tes-keycloak-wiremocks:1.0.0-SNAPSHOT'
    implementation 'org.apache.groovy:groovy-all:5.0.5'
}
