# ===================================================================
#                   Docker Configuration
# ===================================================================
docker.image.name=@serviceDockerImageName@
docker.image.tag=@version@
features.service.key=tes-features-service
